# Generated by Django 4.2.9 on 2024-01-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_image_remove_task_image_task_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(default=2018, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
