# Generated by Django 4.2.9 on 2024-01-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_image_image_remove_task_images_task_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
