# Generated by Django 4.2.9 on 2024-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('low', 1), ('medium', 2), ('high', 3)], max_length=10),
        ),
    ]
